# Generated by Django 2.1.2 on 2018-10-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appEstacoes', '0001_initial'),
        ('appGates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leitura_entrada', models.IntegerField(blank=True, null=True)),
                ('leitura_saida', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('estacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEstacoes.Estacao')),
                ('gates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGates.Gate')),
            ],
        ),
    ]
