# Generated by Django 2.1.2 on 2018-10-21 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(choices=[('CHI', '1 - Chico da Silva'), ('JAL', '2 - José de Alencar'), ('SBE', '3 - São Benedito'), ('BEN', '4 - Benfica'), ('PCI', '5 - Padre Cícero'), ('POR', '6 - Porangabussu'), ('COU', '7 - Couto Fernandes'), ('JUK', '8 - Juscelino Kubsheck'), ('PAR', '9 - Parangaba'), ('VIP', '10 - Vila Pery'), ('SAT', '11 - Manoel Sátiro'), ('MON', '12 - Mondubim'), ('ESP', '13 - Esperança'), ('ARA', '14 - Aracapé'), ('ALT', '15 - Alto Alegre'), ('RAQ', '16 - Raquel de Queiróz'), ('VIT', '17 - Virgílio Távora'), ('MAR', '18 - Maracanaú'), ('JER', '19 - Jereissati'), ('CAB', '20 - Carlito Benevides')])),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
